server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmsystem?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml